### PR TITLE
Fix for the Thread Message Issue

### LINKED ISSUE #19: Habla doesn't work inside threads
- Habla doesn't respond to any text commands inside threads
- You can @ habla to invite him into a thread but even if he's there, he doesn't respond to anything
- According to logs his `messageCreate` event isn't even getting triggered

### PR DESCRIPTION
**Pull request by LostNuke**
Had to change the discord version to the recent version and add Intents and change from the deprecated message Event to messageCreate.

Fixes #19

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ const messageHandler = require('./handlers/message.handler');
 const guildCreateHandler = require('./handlers/guild-create.handler');
 const logger = require('./util/logger');
 
-const client = new Discord.Client();
+const client = new Discord.Client({ intents: new Discord.Intents(37379) });
```
Comment (gganon) [inline src/index.js:7]: I'm unfamiliar with this. Can you tell me what it does and what the `37379` constant means?

File: package.json [hunk 2]
```diff
@@ -15,7 +15,7 @@
   "license": "UNLICENSE",
   "dependencies": {
     "axios": "^0.21.2",
-    "discord.js": "git://github.com/discordjs/discord.js#cee6cf70ce76e9b06dc7f25bfd77498e18d7c8d4",
+    "discord.js": "^13.8.0",
```
Comment (gganon) [inline package.json:18]: Thanks! Nice catch!

This change should have caused `package-lock.json` to update as well... did that happen on your system? If so, please add the package-lock change to the PR as well

**Review by gganon — CHANGES_REQUESTED** [review]

**Comment by gganon** [comment]
Unit tests are also failing but it looks like that might be because the new Discord.js client requires a newer version of Node.js. Leave that part to me, I'll take a look at it before merging

File: src/index.js (hunk 1 above)
Comment (LostNuke) [reply src/index.js:7]: Basically its the Bitfield for the Intents, which discords websocket uses to know which Events to send you. You can calculate them or like use websites like this https://ziad87.net/intents/. 37379 Is basically the intent bitfield for GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, DIRECT_MESSAGES and MESSAGE_CONTENT. Should pretty much give you all the events you would need.

File: package.json (hunk 2 above)
Comment (LostNuke) [reply package.json:18]: Ye uploaded that too

File: src/index.js (hunk 1 above)
Comment (gganon) [reply src/index.js:7]: Nice.

As we discussed offline, we're going to change this code to use the array syntax with constants (like [this](https://discordjs.guide/popular-topics/intents.html#enabling-intents) so that the list of intents is clear to someone reading the code

And we're also going to reduce the list of intents to the minimum habla needs which is GUILDS, GUILDS_MESSAGES and MESSAGE_CONTENT

**Review by gganon — APPROVED** [review]
